"""update table Film, add url film

Revision ID: 15c81c717910
Revises: fa3ae38c3207
Create Date: 2025-03-31 17:09:28.744794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c81c717910'
down_revision = 'fa3ae38c3207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url_film', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_column('url_film')

    # ### end Alembic commands ###
