"""add Actor, ActorFilm tables

Revision ID: 98bdd03d29ae
Revises: 42d8bdf3893c
Create Date: 2025-04-06 16:00:33.795581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bdd03d29ae'
down_revision = '42d8bdf3893c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor')
    # ### end Alembic commands ###
